version: '3.3'

volumes:
  static:
  backend_static:
  backend_media:
  pg_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  frontend:
    env_file: .env
    image: ilyarez/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/app/result_build/build

  backend:
    image: ilyarez/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/

  nginx:
    image: ilyarez/foodgram_gateway
    ports:
      - "5000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
